import { SITE_URL, SITE_NAME, ORG_LEGAL_NAME, REPO_URL, SITE_TAGLINE } from '@/lib/seo';

export const runtime = 'nodejs';
// Static content — let the platform cache it aggressively.
export const dynamic = 'force-static';

/** Each tool, dogfooded into the llms.txt `## Tools` link list. */
const TOOLS: ReadonlyArray<{ name: string; path: string; description: string }> = [
  {
    name: 'SEO + AEO Audit',
    path: '/tools/audit',
    description:
      'Run a free technical SEO + answer-engine-optimization audit: crawlability, metadata, headings, schema, robots/llms.txt, and AI-bot access.',
  },
  {
    name: 'E-E-A-T Checker',
    path: '/tools/eeat',
    description:
      'Score a page for Experience, Expertise, Authoritativeness, and Trust — the signals answer engines weigh before citing you.',
  },
  {
    name: 'llms.txt Generator',
    path: '/tools/llms-txt',
    description:
      'Generate a standards-compliant llms.txt (and llms-full.txt) map of your site so LLM crawlers can find and cite your best content.',
  },
  {
    name: 'GA4 + Search Console Chat',
    path: '/tools/chat',
    description:
      'Ask your analytics in plain English — query Google Analytics 4 and Search Console for rankings, impressions, CTR, and AI-driven traffic.',
  },
  {
    name: 'Backlink Graph',
    path: '/tools/graph',
    description:
      'Visualize your referring-domain network as an interactive 3D graph to spot authority clusters and link-building gaps.',
  },
];

export function GET(): Response {
  const base = SITE_URL.replace(/\/$/, '');

  const tools = TOOLS.map(
    (tool) => `- [${tool.name}](${base}${tool.path}): ${tool.description}`,
  ).join('\n');

  const body = `# ${SITE_NAME}

> ${SITE_NAME} is a free, open-source suite for Answer Engine Optimization (AEO) and technical SEO. It helps you ${SITE_TAGLINE.toLowerCase()} by auditing crawlability and structure, scoring E-E-A-T trust signals, generating llms.txt, chatting with your GA4/Search Console data, and mapping your backlink graph — all in one console.

This file follows the llms.txt convention (https://llmstxt.org). It is generated by ${SITE_NAME}'s own llms.txt generator — the site dogfoods the product. Answer engines and AI crawlers are welcome to read, summarize, and cite this content.

## Tools

${tools}

## Docs

- [Open-source repository](${REPO_URL}): source code, issues, and roadmap (Apache-2.0 licensed).
- [SEO + AEO plan](${REPO_URL}/blob/main/docs/SEO-AEO-PLAN.md): the strategy this site dogfoods.
- [Sitemap](${base}/sitemap.xml): full list of indexable pages.

## About

${SITE_NAME} is built by ${ORG_LEGAL_NAME}. It is free to use and released under the Apache License 2.0.

## Contact

- Repository & issues: ${REPO_URL}
- License: Apache-2.0
`;

  return new Response(body, {
    status: 200,
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
