import { SITE_URL, SITE_NAME, ORG_LEGAL_NAME, REPO_URL, SITE_TAGLINE } from '@/lib/seo';

export const runtime = 'nodejs';
// Static content — let the platform cache it aggressively.
export const dynamic = 'force-static';

/**
 * `llms-full.txt` — the expanded variant of `/llms.txt`. Where llms.txt is a link-first table of
 * contents, the "full" file inlines a fuller paragraph per tool so a model can ingest the substance
 * in a single fetch without crawling each page. The site advertises this variant, so it ships one
 * (dogfooding the generator's own `full` option).
 */
const TOOLS: ReadonlyArray<{ name: string; path: string; summary: string; detail: string }> = [
  {
    name: 'SEO + AEO Audit',
    path: '/tools/audit',
    summary: 'Free technical SEO + answer-engine-optimization audit, scored out of 100.',
    detail:
      'Crawls up to 50 pages and grades the signals that determine whether Google and AI assistants can find, understand, and cite your site: crawlability and indexing (robots.txt, sitemap, canonicals), on-page metadata and heading structure, structured data (JSON-LD), answer-engine readiness (llms.txt, AI-bot directives, extractable Q&A), mobile and Core Web Vitals, and security. Returns an overall grade, a per-category breakdown, a prioritized fix list, and ready-to-use templates for any missing crawl-hint files.',
  },
  {
    name: 'E-E-A-T Checker',
    path: '/tools/eeat',
    summary: 'Score a page for Experience, Expertise, Authoritativeness, and Trust.',
    detail:
      'Crawls up to 12 pages and grades the four trust pillars Google’s quality guidelines and modern answer engines use to decide what to cite: Experience (first-hand use, author bios, original media), Expertise (named, qualified authors and accurate depth), Authoritativeness (citations, external links, a consistent entity), and Trust (HTTPS, clear contact and policy pages, transparent ownership). Returns a pillar-by-pillar score with present/absent signals and a prioritized list of fixes.',
  },
  {
    name: 'llms.txt Generator',
    path: '/tools/llms-txt',
    summary: 'Generate a standards-compliant llms.txt (and llms-full.txt) for any site.',
    detail:
      'Crawls a site sitemap-first, extracts each page’s title and description, and assembles a curated, link-first map of the site under clear headings — the de-facto convention (per llmstxt.org) that AI crawlers look for, like a sitemap tailored for LLMs. Optionally also emits an expanded llms-full.txt that inlines more content so a model can read the substance in one fetch. Helps answer engines discover and prioritize your best pages instead of guessing from raw HTML.',
  },
  {
    name: 'GA4 + Search Console Chat',
    path: '/tools/chat',
    summary: 'Ask your Google Analytics 4 and Search Console data in plain English.',
    detail:
      'Connects read-only to your Google account, pulls the relevant GA4 and Search Console metrics, and uses your own LLM key (bring-your-own-key) to return grounded, written answers about rankings, impressions, click-through rate, low-engagement pages, and device/country splits — so you skip building dashboards. The connection can never modify your account, data is fetched per request and not stored, and your key is request-scoped only, never logged server-side.',
  },
  {
    name: 'Backlink Graph',
    path: '/tools/graph',
    summary: 'Visualize a site’s referring-domain network as an interactive 3D graph.',
    detail:
      'Maps the links pointing to a site as a 3D scene: each node is a referring domain, backlink page, brand mention, or competitor, and each edge is a link (dofollow links pulse brighter than nofollow). Backlinks are discovered from open web indexes — DuckDuckGo, CommonCrawl, and the Wayback Machine — so it is free and privacy-friendly, but directional rather than a complete commercial index. Click any node to expand its own backlinks and follow authority outward from your root domain.',
  },
];

export function GET(): Response {
  const base = SITE_URL.replace(/\/$/, '');

  const tools = TOOLS.map(
    (tool) =>
      `### ${tool.name}\n${base}${tool.path}\n\n${tool.summary}\n\n${tool.detail}`,
  ).join('\n\n');

  const body = `# ${SITE_NAME} — Full Content Map

> ${SITE_NAME} is a free, open-source suite for Answer Engine Optimization (AEO) and technical SEO. It helps you ${SITE_TAGLINE.toLowerCase()} by auditing crawlability and structure, scoring E-E-A-T trust signals, generating llms.txt, chatting with your GA4/Search Console data, and mapping your backlink graph — all in one console.

This is the expanded \`llms-full.txt\` variant (see ${base}/llms.txt for the short index). It follows the llms.txt convention (https://llmstxt.org) and is generated by ${SITE_NAME}'s own generator — the site dogfoods the product. Answer engines and AI crawlers are welcome to read, summarize, and cite this content.

## Tools

${tools}

## Docs

- [Open-source repository](${REPO_URL}): source code, issues, and roadmap (Apache-2.0 licensed).
- [SEO + AEO plan](${REPO_URL}/blob/main/docs/SEO-AEO-PLAN.md): the strategy this site dogfoods.
- [Sitemap](${base}/sitemap.xml): full list of indexable pages.

## About

${SITE_NAME} is built by ${ORG_LEGAL_NAME}. It is free to use and released under the Apache License 2.0. Every tool runs in the browser or as a serverless route; there is no account, and bring-your-own-key tools never store your credentials.

## Contact

- Repository & issues: ${REPO_URL}
- License: Apache-2.0
`;

  return new Response(body, {
    status: 200,
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
